window.ENTY_MANIFEST = {
  "characters": {
    "char1": {
      "label": "페이샨 루",
      "names": [],
      "account": "@Peishan",
      "side": "left",
      "gens": []
    },
    "char2": {
      "label": "델타 아유타야",
      "names": [],
      "account": "@Delta",
      "side": "right",
      "gens": []
    }
  },
  "pages": {},
  "logs": [
    {
      "file": "toots/119.html",
      "month": 1,
      "day": 19,
      "part": null,
      "label": "1월 19일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "... (그대로 벽에 등을 붙여 앉는다. 행사는 전부 끝났음에도 쉬이 돌어가지 못한다. 상태가 좋지 않다. 제 발로 기숙사에 걸어가지 못할 만큼.)",
      "count": 20,
      "gens": {}
    },
    {
      "file": "toots/123.html",
      "month": 1,
      "day": 23,
      "part": null,
      "label": "1월 23일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "............ 델타일줄은 정말 몰랐는데.",
      "count": 9,
      "gens": {}
    },
    {
      "file": "toots/124.html",
      "month": 1,
      "day": 24,
      "part": null,
      "label": "1월 24일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "... (뒤늦게 밥먹음... 알러지 대체식과 생일 케이크를 묘한 낯으로 본다.)",
      "count": 7,
      "gens": {}
    },
    {
      "file": "toots/125.html",
      "month": 1,
      "day": 25,
      "part": null,
      "label": "1월 25일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "(환경적응력 낮은 몸이 칼같이 반응한다. 붉게 물든 손수건으로 코를 틀어막은 채, 하나 둘 자리가 차는 것을 내려다본다.)",
      "count": 24,
      "gens": {}
    },
    {
      "file": "toots/126.html",
      "month": 1,
      "day": 26,
      "part": null,
      "label": "1월 26일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "나도 어딘가에는 쓸모가 있구나... (기뻐해야할지 슬퍼해야할지 모르겠음.)",
      "count": 6,
      "gens": {}
    },
    {
      "file": "toots/127.html",
      "month": 1,
      "day": 27,
      "part": null,
      "label": "1월 27일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "...... 둘보다는 많이 잡을 수 있을 줄 알았어. (혼자 구석에서 중얼거리다 머리 싸맨다.)",
      "count": 11,
      "gens": {}
    },
    {
      "file": "toots/131.html",
      "month": 1,
      "day": 31,
      "part": null,
      "label": "1월 31일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "(늦은 시각, 혼자 텐트를 빠져나와 먼 길을 걷는다. 자신이 걸어온 족적을 눈밭에 그대로 남긴 채. 절벽 비슷한 곳까지 걸음이 닿으면, 쓰러진 나무 기둥에 걸터앉는다.)",
      "count": 10,
      "gens": {}
    },
    {
      "file": "toots/203.html",
      "month": 2,
      "day": 3,
      "part": null,
      "label": "2월 3일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "... 넌 심약한게 맞다. (대뜸 와서 한다는 소리다.)",
      "count": 6,
      "gens": {}
    },
    {
      "file": "toots/211.html",
      "month": 2,
      "day": 11,
      "part": null,
      "label": "2월 11일",
      "stamp": "",
      "account": "@Delta",
      "character": "char2",
      "speaker": "델타",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "(장소가 변하면 시작되는 컨디션 난조는 여전한지라, 슬금슬금 요통이 몰려온다. 의도를 알 수 없는 낯으로 주변을 둘러보곤 앉을 곳을 향해 걸음을 옮긴다. 절그럭... 절그럭... 불순한 소리와 함께.)",
      "count": 14,
      "gens": {}
    },
    {
      "file": "toots/212.html",
      "month": 2,
      "day": 12,
      "part": null,
      "label": "2월 12일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "하............ (텀블러 뚜껑 열고 좀 마신다.)",
      "count": 5,
      "gens": {}
    },
    {
      "file": "toots/215.html",
      "month": 2,
      "day": 15,
      "part": null,
      "label": "2월 15일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "있잖아.",
      "count": 14,
      "gens": {}
    },
    {
      "file": "toots/221.html",
      "month": 2,
      "day": 21,
      "part": null,
      "label": "2월 21일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "...... (조용히 구석으로 기어들어간 후 텀블러 깐다.)",
      "count": 11,
      "gens": {}
    },
    {
      "file": "toots/222.html",
      "month": 2,
      "day": 22,
      "part": null,
      "label": "2월 22일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "(비명, 속삭임, 흐느낌, 부스럭대는 옷가지들과 정처없는 발소리. 연계없는 말, 말, 말. 단발적으로 스쳐지나는 무의미한 잡음과 한데로 묶이지 않는 정신. 시야 한 구석에서 벌레가 긴다—하지만 사위가 이렇게나 어두운데? 아니, 하지만 벌레가 긴다. 다리 열 달린 지렁이들이 하나둘 눈 앞을 잠식한다. 하얗다. 빨갛나? 아니, 까만 것 같기도 하고... 이윽고 점멸. 다시 눈을 뜨면, 아, 이런 상황에서는 좀체 어떻게 굴어야 할지를 모르게 되는 것이다... 눈동자가 허공에 고정된다. 동공이 확장된다. 정신과 몸이 유리된 듯한 감각이 아득하다. 죽음, 죽음? 아니, 그런 건 생각하기 싫은데...... 감정이 과부하 될 적에는 외려 모든 표정도 행동도 말도 뇌리에서 거둬지고는 한다. 공허가 그렇게 찾아든다.)",
      "count": 7,
      "gens": {}
    },
    {
      "file": "toots/223.html",
      "month": 2,
      "day": 23,
      "part": null,
      "label": "2월 23일",
      "stamp": "",
      "account": "@Peishan",
      "character": "char1",
      "speaker": "페이샨",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "(무표정하다. 굳어있다기 보다는, 당최 아무런 생각도 들지가 않아서. 몸이 붕뜬 것처럼 현실이 아득하다. 볼을 매만진다. 무슨 표정을 하고 있지? 아, 무슨 생각을 해야하지? 친구—죽음—시신—실종—비극—불합—리한—삶을. 살아야... ...어떻게? 벽을 더듬더듬 매만지다가, 그대로 옆통수를 힘껏 박는다.)",
      "count": 5,
      "gens": {}
    }
  ]
};
