window.ENTY_MANIFEST = {
  "characters": {
    "char1": {
      "label": "페이샨 루",
      "names": [],
      "account": "@Peishan",
      "side": "left",
      "gens": []
    },
    "char2": {
      "label": "델타 아유타야",
      "names": [],
      "account": "@Delta",
      "side": "right",
      "gens": []
    }
  },
  "pages": {},
  "logs": [
    {
      "file": "toots/119.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 19일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "",
      "count": 19,
      "gens": {}
    },
    {
      "file": "toots/123.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 23일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "",
      "count": 8,
      "gens": {}
    },
    {
      "file": "toots/124.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 24일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "",
      "count": 6,
      "gens": {}
    },
    {
      "file": "toots/125.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 25일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "",
      "count": 23,
      "gens": {}
    },
    {
      "file": "toots/126.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 26일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "",
      "count": 5,
      "gens": {}
    },
    {
      "file": "toots/127.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 27일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/C7Ort0C.png",
      "text": "",
      "count": 10,
      "gens": {}
    },
    {
      "file": "toots/131.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "1월 31일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "",
      "count": 9,
      "gens": {}
    },
    {
      "file": "toots/211.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 11일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/folLETD.png",
      "text": "",
      "count": 13,
      "gens": {}
    },
    {
      "file": "toots/212.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 12일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "",
      "count": 4,
      "gens": {}
    },
    {
      "file": "toots/215.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 15일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "",
      "count": 13,
      "gens": {}
    },
    {
      "file": "toots/221.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 21일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "",
      "count": 10,
      "gens": {}
    },
    {
      "file": "toots/222.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 22일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "",
      "count": 6,
      "gens": {}
    },
    {
      "file": "toots/223.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "2월 23일",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/JXsff78.png",
      "text": "",
      "count": 4,
      "gens": {}
    },
    {
      "file": "toots/23.html",
      "month": 0,
      "day": 0,
      "part": null,
      "label": "23",
      "stamp": "",
      "account": "' + accounts[name] + '",
      "character": "",
      "speaker": "",
      "avatar": "https://i.imgur.com/KZ411UH.png",
      "text": "",
      "count": 5,
      "gens": {}
    }
  ]
};
